name: 'Build'

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          npm install
          npm run build
